name: private-proxy-1
directory:
  type: json
  settings:
    path: "$DIR/../../directory/services.json"
channels: # defines all the channels that we want to open when starting the server
  - name: main gRPC client # creates outgoing gRPC connections to deliver and receive messages
    type: grpc_client
    settings:
      tls:
        ca_certificate_file: "$DIR/../../certs/root.crt"
        certificate_file: "$DIR/../../certs/private-proxy-1.crt"
        key_file: "$DIR/../../certs/private-proxy-1.key"
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server
    settings:
      bind_address: "0.0.0.0:7766"
      tls:
        ca_certificate_file: "$DIR/../../certs/root.crt"
        certificate_file: "$DIR/../../certs/private-proxy-1.crt"
        key_file: "$DIR/../../certs/private-proxy-1.key"
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: http://private-proxy:8877/jsonrpc
      #tls:
      #  ca_certificate_file: "$DIR/../../certs/root.crt"
