# required, set via CLI
#   test: --set environment=test
#   production: --set environment=production
environment: undefined

tls:
  keystoreSecretName: tls-keystore
  keystoreCredentialsSecretName: tls-keystore-credentials
  mountPath: /tls

public:
  image: inoeg/iris-public-server:0.0.1-SNAPSHOT
  port: 8443
  paths:
    - /

location:
  image: inoeg/iris-location-service:0.0.1-SNAPSHOT
  port: 8080
  paths:
    - /search
    - /search-index

postgres:
  storageDir: /var/lib/postgresql/data/pgdata
  port: 5432

domains:
  test: test.iris-gateway.de
  production: iris-gateway.de
