apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iris-gateway.public" . }}
  labels:
    {{- include "iris-gateway.public-labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "iris-gateway.public-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iris-gateway.public-labels" . | nindent 8 }}
    spec:
      containers:
        - name: public
          image: {{ .Values.public.image }}
          {{- if eq .Values.environment "local" }}
          imagePullPolicy: Never
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: https
              containerPort: {{ .Values.public.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "iris-gateway.postgres" . }}
            - secretRef:
                name: {{ .Values.tls.keystoreCredentialsSecretName }}
          volumeMounts:
            - mountPath: {{ .Values.tls.mountPath }}
              name: tls-keystore
              readOnly: true
          env:
            - name: KEYSTORE_PATH
              value: {{ .Values.tls.mountPath }}/keystore.jks
      volumes:
        - name: tls-keystore
          secret:
            secretName: {{ .Values.tls.keystoreSecretName }}
