apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "iris-gateway.service-directory-backup" . }}
  labels:
    {{- include "iris-gateway.service-directory-backup-labels" . | nindent 4 }}
spec:
  schedule: '@midnight'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "iris-gateway.service-directory-backup-labels" . | nindent 12 }}
          annotations:
            checksum/scripts: {{ include (print $.Template.BasePath "/service-directory-backup/configmap.yaml") . | sha256sum }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ubuntu
              image: ubuntu
              imagePullPolicy: {{ .Values.global.PullPolicy }}
              command: [ /scripts/backup.sh ]
              volumeMounts:
                - mountPath: {{ .Values.serviceDirectory.storageDir }}
                  name: backup-from
                - mountPath: {{ .Values.serviceDirectory.backupDir }}
                  name: backup-to
                - mountPath: /scripts
                  name: scripts
                  readOnly: true
          volumes:
            - name: backup-from
              persistentVolumeClaim:
                claimName: {{ include "iris-gateway.service-directory" . }}
            - name: backup-to
              persistentVolumeClaim:
                claimName: {{ include "iris-gateway.service-directory-backup" . }}
            - name: scripts
              configMap:
                name: {{ include "iris-gateway.service-directory-backup" . }}
                defaultMode: 0755
