apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-gateway.locations-postgres" . }}
  labels:
  {{- include "iris-gateway.locations-postgres-labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: locations-postgres
  resources:
    requests:
      storage: 10Gi
