apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "iris-gateway.fullname" . }}-alerts
spec:
  groups:
    - name: kube-state-metrics
      rules:
        - alert: KubernetesPodNotStarting
          expr: kube_pod_container_status_waiting_reason{namespace="iris-gateway", reason!="ContainerCreating"} == 1
          annotations:
            message: "Pod {{ "{{ $labels.pod }}" }} is not able to start: {{ "{{ $labels.reason }}" }}\n  LABELS: {{ "{{ $labels }}" }}"
            summary: Pod is not able to start
          for: 1m
          labels:
            receiver: iris-alerts-{{ .Values.environment }}
            severity: critical
        - alert: KubernetesPodRestartingTooOften
          expr: rate(kube_pod_container_status_restarts_total{namespace="iris-gateway"}[5m]) * 60 * 5 > 0
          annotations:
            message: "Pod {{ "{{ $labels.pod }}" }} is restarting too often: {{ "{{ $value }}" }} times / 5 minutes\n  LABELS: {{ "{{ $labels }}" }}"
            summary: Pod is restarting too often
          for: 15m
          labels:
            receiver: iris-alerts-{{ .Values.environment }}
            severity: warning
        - alert: OpenFileDescriptorsTooHigh
          expr: sum(process_open_fds{namespace="iris-gateway"}) > 1024
          annotations:
            message: "Too many open files in namespace iris-gateway : {{ "{{ $value }}" }}"
            summary: Open filedescriptors too high
          for: 1m
          labels:
            receiver: iris-alerts-{{ .Values.environment }}
            severity: warning
