apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "iris-gateway.fullname" . }}-alerts
spec:
  groups:
    - name: kube-state-metrics
      rules:
        - alert: KubernetesPodCrashLooping
          annotations:
            message: "Pod {{ "{{ $labels.pod }}" }} is crash looping\n  LABELS: {{ "{{ $labels }}" }}"
            summary: Kubernetes pod repeatedly restarting
          expr: increase(kube_pod_container_status_restarts_total{namespace="{{ .Release.Namespace }}"}[1m]) > 3
          for: 1m
          labels:
            receiver: iris-alerts-{{ .Values.environment }}
            severity: critical
