apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iris-gateway.fullname" . }}-eps-actuator
spec:
  endpoints:
    - interval: 15s
      path: /prometheus
      port: iris-gateway-locations-eps-prometheus
  selector:
    matchLabels:
      prometheusMetricsType: eps-actuator
