openapi: '3.0.2'
info:
  title: IRIS Location Service - Private API
  version: '0.1.0'
paths:
  /search/{search_keyword}:
    get:
      parameters:
        - in: path
          required: true
          description: The search keyword
          name: search_keyword
          schema: 
            type: string
            minimum: 4
      responses:
        '200':
          $ref: '#/components/responses/SearchResponse'
        
          
components:
  responses:
    NotFound:
      description: 'The specified resource was not found.'
    Unauthorized:
      description: 'The client is unauthorized to access this API.'
    UnprocessableEntity:
      description: 'The transferred entity is not expected for the data request.'
    SearchResponse:
      description: The response for the location search
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LocationList'

  parameters:
    Code:
      name: code
      in: path
      required: true
      description: 'The unique code of a data request in format of a UUID sent by the health department.'
      schema:
        type: string
#        pattern: '^[2-9A-HKMNP-Z]{4}-[2-9A-HKMNP-Z]{4}-[2-9A-HKMNP-Z]{4}$'
    LocationId:
      name: id
      in: path
      required: true
      description: 'The unique ID of a location in the context of the provider.'
      schema:
        type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-IRIS-API-KEY
      in: header
        
  schemas:
    LocationList:
      type: object
      required:
        - "locations"
      properties:
        locations: 
          type: array
          items:
            $ref: '#/components/schemas/LocationInformation'          
    LocationInformation:
      type: object
      required:
        - "id"
        - "name"
        - "contact"
      properties:
        id:
          type: string
          description: 'Interne ID (beim Provider)'
          example: '5eddd61036d39a0ff8b11fdb'
        name:
          type: string
          description: 'Name des Standorts'
          example: 'Restaurant Alberts'
        publicKey:
          type: string
          description: 'Öffentlicher Schlüssel, ggf. für Nachrichtenaustausch'
        contact:
          $ref: '#/components/schemas/LocationContact'
        contexts:
          type: array
          items:
            $ref: '#/components/schemas/LocationContext'
    LocationContact:
      description: 'Kontaktperson des Standorts'
      type: object
      required:
        - "address"
      properties:
        officialName:
          type: string
          description: 'Offizieller Unternehmensname'
          example: 'Darfichrein GmbH'
        representative:
          type: string
          description: 'Ansprechpartner für dieses Unternehmen'
          example: 'Silke '
        address:
          $ref: '#/components/schemas/LocationAddress'
        ownerEmail:
          type: string
          description: 'E-Mail des Inhabers'
          example: 'covid@restaurant.de'
        email:
          type: string
          description: 'ggf. E-Mail einer weiteren Kontaktperson'
          example: 'covid2@restaurant.de'
        phone:
          type: string
          description: 'Telefonnummer eines Ansprechpartners'
          example: 'die bleibt privat :-)'
    LocationContext:
      type: object
      description: 'Ein Standort hat ggf. weitere Informationen wie Tische/Räume, etc.'
      required:
        - "id"
        - "name"
      properties:
        id:
          type: string
          description: 'Interne ID des Kontext'
          example: '5f4bfff742c1bf5f72918851'
        name:
          type: string
          description: 'Bezeichnung'
          example: 'Raum 0815'
    LocationAddress:
      description: 'Anschrift des Standorts'
      required:
        - street
        - city
        - zip
      properties:
        street:
          type: string
          description: 'street + number'
          example: 'Türkenstr. 7'
        city:
          type: string
          description: 'Stadt'
          example: 'München'
        zip:
          type: string
          description: 'Postleitzahl'
          example: '80333'
