apiVersion: v1
kind: Service
metadata:
  name: {{ include "iris-gateway.location" . }}
  labels:
    {{- include "iris-gateway.location-labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.location.port }}
      targetPort: https
      protocol: TCP
      name: http
  selector:
    {{- include "iris-gateway.location-labels" . | nindent 4 }}
