apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iris-gateway.locations-eps" . }}
data:
  settings.yml: |
    name: ls-1
    directory:
      type: json
      settings:
        path: "{{ .Values.eps.configMountPath }}/services.json"
    channels:  # defines all the channels that we want to open when starting the server
      - name: Stdout channel
        type: stdout
        settings: {}
      - name: main gRPC server  # accepts incoming gRPC connections to deliver and receive messages
        type: grpc_server
        settings:
          bind_address: "0.0.0.0:{{ .Values.locations.nodePort }}"
          tls:
            ca_certificate_file: "{{ .Values.tls.mountPath }}/root.crt"
            certificate_file: "{{ .Values.tls.mountPath }}/ls-1.crt"
            key_file: "{{ .Values.tls.mountPath }}/ls-1.key"
      - name: main JSON-RPC client  # creates outgoing JSONRPC connections to deliver and receive messages
        type: jsonrpc_client
        settings:
          # needs to match the endpoint configuration in the spring boot app
          endpoint: http://{{ include "iris-gateway.locations" . }}:{{ .Values.locations.port }}/location-rpc
  services.json: |
    {
      "entries": [
        {
          "name": "ls-1",
          "channels": [
            {
              "type": "grpc_server",
              "settings": {
                "address": "locations.{{ index .Values.domains .Values.environment }}"
              }
            }
          ]
        }
      ]
    }
