apiVersion: v1
kind: Service
metadata:
  name: {{ include "iris-gateway.locations-eps" . }}
  labels:
    {{- include "iris-gateway.locations-eps-labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "{{ .Values.eps.prometheus.scrape }}"
    prometheus.io/scheme: "{{ .Values.eps.prometheus.scheme }}"
    prometheus.io/path: "{{ .Values.eps.prometheus.path }}"
    prometheus.io/port: "{{ .Values.eps.prometheus.port }}"
spec:
  type: NodePort
  ports:
    - port: {{ .Values.nodePorts.locationsEps }}
      targetPort: grpc
      nodePort: {{ .Values.nodePorts.locationsEps }}
      protocol: TCP
      name: grpc
  type: ClusterIP
  ports:
    - port: {{ .Values.eps.prometheus.port }}
      targetPort: http
      name: prometheus
      protocol: TCP
  selector:
    {{- include "iris-gateway.locations-eps-labels" . | nindent 4 }}
