apiVersion: v1
kind: Service
metadata:
  name: {{ include "iris-gateway.locations-eps" . }}-prometheus
  labels:
    {{- include "iris-gateway.locations-eps-labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "{{ .Values.eps.prometheus.scrape }}"
    prometheus.io/scheme: "{{ .Values.eps.prometheus.scheme }}"
    prometheus.io/path: "{{ .Values.eps.prometheus.path }}"
    prometheus.io/port: "{{ .Values.eps.prometheus.port }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.eps.prometheus.port }}
      protocol: TCP
      name: iris-gateway-locations-eps-prometheus
      targetPort: prometheus
  selector:
    {{- include "iris-gateway.locations-eps-labels" . | nindent 4 }}
