apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iris-gateway.public-proxy" . }}
data:
  settings.yml: |
    public:
      name: {{ (index .Values.serviceNames .Values.environment).publicProxy }}
      database_file: {{ .Values.publicProxy.persistentStoragePath }}/public-proxy-announcements.db
      tls_bind_address: 0.0.0.0:{{ .Values.nodePorts.publicProxyTls }}
      internal_bind_address: 0.0.0.0:{{ .Values.nodePorts.publicProxyInternal }}
      internal_endpoint: {{ .Values.environment }}.iris-gateway.de:{{ .Values.nodePorts.publicProxyInternal }}
      jsonrpc_client:
        endpoint: https://{{ include "iris-gateway.public-proxy-eps" . }}:{{ .Values.publicProxyEps.jsonRpcPort }}/jsonrpc
        tls:
          certificate_file: "{{ .Values.tls.mountPath }}/{{ (index .Values.serviceNames .Values.environment).publicProxy }}.crt"
          key_file: "{{ .Values.tls.mountPath }}/{{ (index .Values.serviceNames .Values.environment).publicProxy }}.key"
          ca_certificate_files:
{{- range (index .Values.tls.rootCertificates .Values.environment) }}
            - "{{ $.Values.tls.mountPath }}/{{ . }}"
{{- end}}
          server_name: {{ (index .Values.serviceNames .Values.environment).publicProxy }}
      jsonrpc_server: # the JSON-RPC server that the EPS server uses for communication
        bind_address: "0.0.0.0:{{ .Values.publicProxy.jsonRpcPort }}"
        tls:
          ca_certificate_files:
{{- range (index .Values.tls.rootCertificates .Values.environment) }}
            - "{{ $.Values.tls.mountPath }}/{{ . }}"
{{- end}}
          certificate_file: "{{ .Values.tls.mountPath }}/{{ (index .Values.serviceNames .Values.environment).publicProxy }}.crt"
          key_file: "{{ .Values.tls.mountPath }}/{{ (index .Values.serviceNames .Values.environment).publicProxy }}.key"
