apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-gateway.public-proxy" . }}
  labels:
  {{- include "iris-gateway.public-proxy-labels" . | nindent 4 }}
spec:
{{- if (eq .Values.environment "test") }}
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: public-proxy
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
{{- end }}
  resources:
    requests:
      storage: 1Gi
