apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-gateway.public-proxy" . }}
  labels:
  {{- include "iris-gateway.public-proxy-labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: public-proxy
  resources:
    requests:
      storage: 1Gi
