apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-gateway.service-directory" . }}
  labels:
  {{- include "iris-gateway.service-directory-labels" . | nindent 4 }}
spec:
{{- if (eq .Values.environment "test") }}
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: service-directory
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
{{- end }}
  resources:
    requests:
      storage: 1Gi
