apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-gateway.service-directory" . }}
  labels:
  {{- include "iris-gateway.service-directory-labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: service-directory
  resources:
    requests:
      storage: 1Gi
