apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-gateway.locations-postgres-backup" . }}
  labels:
  {{- include "iris-gateway.locations-postgres-backup-labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: locations-postgres-backups
  resources:
    requests:
      storage: 10Gi
