apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-gateway.locations-postgres-backup" . }}
  labels:
  {{- include "iris-gateway.locations-postgres-backup-labels" . | nindent 4 }}
spec:
{{- if (eq .Values.environment "test") }}
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: locations-postgres-backups
{{- else }}
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
{{- end }}
  resources:
    requests:
      storage: 10Gi
