apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iris-gateway.locations" . }}
  labels:
    {{- include "iris-gateway.locations-labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "iris-gateway.locations-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iris-gateway.locations-labels" . | nindent 8 }}
    spec:
      containers:
        - name: location
          image: {{ .Values.locations.image }}:{{ .Values.locations.tag }}
          {{- if eq .Values.environment "local" }}
          imagePullPolicy: Never
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.locations.port }}
              protocol: TCP
