apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iris-gateway.locations" . }}
  labels:
    {{- include "iris-gateway.locations-labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "iris-gateway.locations-labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "iris-gateway.locations-labels" . | nindent 8 }}
    spec:
      containers:
        - name: location
          image: {{ .Values.locations.image }}:{{ .Values.locations.tag }}
          imagePullPolicy: {{ include "iris-gateway.pullPolicy" . }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgresqlha.postgresql.database }}
            - name: IRIS_MESSAGES_SLACK_TOKEN
              value: {{ .Values.locations.slack.token }}
            - name: IRIS_MESSAGES_SLACK_CHANNEL
              value: {{ .Values.locations.slack.channel }}
            - name: IRIS_MESSAGES_ZAMMAD_TOKEN
              value: {{ .Values.locations.zammad.token }}
            - name: IRIS_MESSAGES_ZAMMAD_API_ADDRESS
              value: {{ .Values.locations.zammad.apiaddress }}
            - name: IRIS_MESSAGES_ZAMMAD_ENVIRONMENT
              value: {{ .Values.locations.zammad.environment }}
            - name: IRIS_MESSAGES_GITHUB_PERSONAL_ACCESS_TOKEN
              value: {{ .Values.locations.github.token }}
            - name: IRIS_MESSAGES_GITHUB_REPO_ORG
              value: {{ .Values.locations.github.org }}
            - name: IRIS_MESSAGES_GITHUB_REPO_NAME
              value: {{ .Values.locations.github.repo }}
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_SEARCH_BACKEND_DIRECTORY_ROOT
              value: {{ .Values.locations.storageDir }}
            - name: HTTP_PROXY
              value: http://{{ .Values.locations.proxy.host }}:{{ .Values.locations.proxy.port }}
            - name: HTTPS_PROXY
              value: http://{{ .Values.locations.proxy.host }}:{{ .Values.locations.proxy.port }}
            - name: http_proxy
              value: http://{{ .Values.locations.proxy.host }}:{{ .Values.locations.proxy.port }}
            - name: https_proxy
              value: http://{{ .Values.locations.proxy.host }}:{{ .Values.locations.proxy.port }}
            - name: _JAVA_OPTIONS
              value: -Dhttp.proxyHost={{ .Values.locations.proxy.host }} -Dhttp.proxyPort={{ .Values.locations.proxy.port }} -Dhttps.proxyHost={{ .Values.locations.proxy.host }} -Dhttps.proxyPort={{ .Values.locations.proxy.port }}
            - name: IRIS_TOKENS_CAT_SALT
              value: {{ .Values.locations.catSalt }}
            - name: IRIS_TOKENS_DAT_SALT
              value: {{ .Values.locations.datSalt }}
          envFrom:
            - secretRef:
                name: {{ include "iris-gateway.locations-postgres" . }}
          livenessProbe:
            httpGet:
              port: {{ .Values.locations.port }}
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: {{ .Values.locations.port }}
              path: /actuator/health/readiness
            initialDelaySeconds: 20
            timeoutSeconds: 5
          ports:
            - name: http
              containerPort: {{ .Values.locations.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.locations.storageDir }}
              name: persistent-storage
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "iris-gateway.locations" . }}-index
