apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-gateway.locations" . }}
  labels:
  {{- include "iris-gateway.locations-labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: locations
  resources:
    requests:
      storage: 10Gi
