name: private-proxy-1
directory:
  # to use the JSON directory, uncomment this and comment everything below...
  type: json
  settings:
    path: "$DIR/../../directory"
channels: # defines all the channels that we want to open when starting the server
  - name: main gRPC server # accepts incoming gRPC connections to deliver and receive messages
    type: grpc_server
    settings:
      bind_address: "0.0.0.0:7776"
      tls:
        ca_certificate_files: [ "$DIR/../../certs/root.crt" ]
        certificate_file: "$DIR/../../certs/private-proxy-1.crt"
        key_file: "$DIR/../../certs/private-proxy-1.key"
  - name: main gRPC client # creates outgoing gRPC connections to deliver and receive messages
    type: grpc_client
    settings:
      tls:
        ca_certificate_files: [ "$DIR/../../certs/root.crt" ]
        certificate_file: "$DIR/../../certs/private-proxy-1.crt"
        key_file: "$DIR/../../certs/private-proxy-1.key"
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server
    settings:
      bind_address: 0.0.0.0:7766
      cors:
        allowed_hosts: [ "^http(?:s)?://localhost\\:\\d+$" ]
      tls:
        ca_certificate_files: [ "$DIR/../../certs/root.crt" ]
        certificate_file: "$DIR/../../certs/private-proxy-1.crt"
        key_file: "$DIR/../../certs/private-proxy-1.key"
        verify_client: false
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: http://private-proxy:8877/jsonrpc
      #tls:
      #  ca_certificate_files: ["$DIR/../../certs/root.crt"]
