########################################################
# provides basic configurations for IRIS client backend and frontend
# this is necessary because extends can't reference to a service with depends_on
########################################################
version: '3'
services:
  iris-client:
    image: inoeg/iris-client-sormas-sidecar:${IRIS_VERSION}
    expose:
      - 8092
    environment: 
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - iris-client.env
    restart: unless-stopped

  iris-frontend:
    image: inoeg/iris-client-frontend:${IRIS_FRONTEND_VERSION}
    expose:
      - 28080
    env_file:
      - iris-client.env
    restart: unless-stopped
