########################################################
# provides SORMAS server together with a Postgresql database
# DB: look at docker-compose-postgres.yml
# SORMAS: look at docker-compose-sormas.base.yml
########################################################
version: '3'
services:
  postgres:
    extends:
      file: docker-compose-postgres.yml
      service: postgres

  sormas:
    extends:
      file: docker-compose-sormas.base.yml
      service: sormas
    depends_on:
      postgres:
        condition: service_healthy
        
volumes:
  psqldata_iris: 
