########################################################
# Intended for the all in one staging environment on the VM 
# 
# provides a NGINX server with certificates and configuration for staging.iris-gateway.de
# togehter with the IRIS applications and with a Postgresql database and SORMAS
# DB: look at docker-compose-postgres.yml
# SORMAS: port = /; look at docker-compose-sormas.base.yml
# IRIS public: port = /
# IRIS location: port = /
# IRIS client: port = /; look at docker-compose-hd-client.base.yml
# IRIS frontend: port = /; look at docker-compose-hd-client.base.yml
# NGINX: port = 443
########################################################
version: '3'
services:

  iris-location:
    image: inoeg/iris-location-service:v1.0.4-alpha
    restart: unless-stopped
    depends_on:
      - ls-1
    expose:
      - 8080

  ls-1:
    image: inoeg/eps:v0.0.4
    depends_on:
      sd-1:
        condition: service_started
    expose:
      - 4445
    ports:
      - 4445:4445
    volumes:
      - "/home/iris/iris-eps/iris-gateway/infrastructure/eps/settings:/app/settings"
    environment:
      - EPS_SETTINGS=settings/dev/roles/ls-1
    command: [ "--level", "debug", "server", "run" ]

  iris-app-api-demo:
    image: inoeg/demo-checkin-app:v1.0.4-alpha
    environment:
      - EPS_CLIENT_CLIENT_URL=https://iris-app-api-demo-eps:5554/jsonrpc
    depends_on:
      iris-location:
        condition: service_started
      iris-app-api-demo-eps:
        condition: service_started
    ports:
      - 8091:8091
    restart: unless-stopped

  iris-app-api-demo-eps:
    image: inoeg/eps:v0.0.4
    depends_on:
      sd-1:
        condition: service_started
    expose:
      - 4444
    ports:
      - 4444:4444
    volumes:
      - "/home/iris/iris-eps/iris-gateway/infrastructure/eps/settings:/app/settings"
    environment:
      - EPS_SETTINGS=settings/dev/roles/demo-app
    command: [ "--level", "trace", "server", "run" ]

  public-proxy:
    image: inoeg/proxy:v0.0.4
    expose:
      - 4433
      - 9999
      - 6655
    ports:
      - 4433:4433
      - 9999:9999
    volumes:
      - "/home/iris/iris-eps/iris-gateway/infrastructure/eps/settings:/app/settings"
      - /home/iris/pub-proxy-db:/tmp
    environment:
      - PROXY_SETTINGS=settings/dev/roles/public-proxy-1
    command: [ "--level", "trace", "run", "public" ]

  public-proxy-eps:
    image: inoeg/eps:v0.0.4
    depends_on:
      sd-1:
        condition: service_started
    expose:
      - 5559
      - 5544
    ports:
      - 5559:5559
    volumes:
      - "/home/iris/iris-eps/iris-gateway/infrastructure/eps/settings:/app/settings"
    environment:
      - EPS_SETTINGS=settings/dev/roles/public-proxy-eps-1
    command: [ "--level", "trace", "server", "run" ]

  sd-1:
    image: inoeg/sd:v0.0.4
    expose:
      - 3322
    ports:
      - 3322:3322
    volumes:
      - "/home/iris/iris-eps/iris-gateway/infrastructure/eps/settings:/app/settings"
      - /home/iris/service-directory:/tmp
    environment:
      - SD_SETTINGS=settings/dev/roles/sd-1
    entrypoint: ./sd
    command: [ "--level", "trace", "run" ]


