########################################################
# Intended for local execution by developers and testers 
# 
# provides full IRIS environment together with a Postgresql database without SORMAS
# DB: look at docker-compose-postgres.yml
# IRIS frontend: port = 28080
########################################################
version: '2.1'
services:
  postgres:
    extends:
      file: docker-compose-postgres.base.yml
      service: postgres

  iris-client:
    extends:
      file: docker-compose-iris-client.base.yml
      service: iris-client
    depends_on:
      postgres:
        condition: service_healthy

  iris-frontend:
    extends:
      file: docker-compose-iris-client.base.yml
      service: iris-frontend
    ports:
      - 28080:28080
    depends_on:
      - iris-client

  nginx:
    extends: 
      file: docker-compose-nginx.base.yml
      service: nginx
    ports:
      - 443:443
    depends_on:
      - iris-frontend
  
volumes:
  psqldata_iris: 
