########################################################
# provides a Postgresql database
# DB: login = postgres:postgres; hostname = postgres; port = 5432; volume = psqldata_iris
########################################################
version: '2.4'
services:
  postgres:
    image: postgres:9.6-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - psqldata_iris:/var/lib/postgresql/data

    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "psql", "-U", "${POSTGRES_USER}", "-c", "SELECT 1;", "${POSTGRES_USER}" ]
      interval: 15s
      timeout: 3s
      retries: 4
      start_period: 30s

volumes:
  psqldata_iris: 
