########################################################
# provides basic configurations for IRIS client backend and frontend
# this is necessary because extends can't reference to a service with depends_on
########################################################
version: '2.1'
services:
  iris-client:
    image: inoeg/iris-client-sormas-sidecar:0.0.1-SNAPSHOT
    expose:
      - 8092
    ports: 
      - 8092:8092
    environment: 
      IRIS_SERVER_ADDRESS:
      IRIS_SERVER_PORT:
      SECURITY_JWT_JWT_SHARED_SECRET:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_USER}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped

  iris-frontend:
    image: inoeg/iris-client-frontend:v0.1.0
    expose:
      - 28080
    environment: 
      SORMAS_SIDECAR_BASE_URL: https://localhost/api
    ports: 
      - 28080:28080
    env_file:
      - .env
    restart: unless-stopped
