{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "iris-gateway.postgres" . }}
data:
  POSTGRES_USER: {{ "postgres" | b64enc }}
  POSTGRES_PASSWORD: {{ "postgres" | b64enc }}
  POSTGRES_HOST: {{ include "iris-gateway.postgres" . | b64enc }}
{{- end }}
