apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iris-gateway.public-proxy-eps" . }}
  labels:
    {{- include "iris-gateway.public-proxy-eps-labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "iris-gateway.public-proxy-eps-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iris-gateway.public-proxy-eps-labels" . | nindent 8 }}
    spec:
      containers:
        - name: public-proxy-eps
          image: {{ .Values.eps.image }}:{{ .Values.epsRepoTag }}
          imagePullPolicy: Always
          args: [--level, trace, server, run]
          ports:
            - name: node-port-eps
              containerPort: {{ .Values.publicProxy.nodePortEps }}
              protocol: TCP
            - name: json-rpc-eps
              containerPort: {{ .Values.publicProxy.jsonRpcPortEps }}
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.tls.mountPath }}
              name: tls
              readOnly: true
            - mountPath: /config
              name: config
              readOnly: true
          env:
            - name: EPS_SETTINGS
              value: {{ .Values.eps.configMountPath }}/settings.yml
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName }}
        - name: config
          configMap:
            name: {{ include "iris-gateway.public-proxy-eps" . }}
