apiVersion: v1
kind: Service
metadata:
  name: {{ include "iris-gateway.public-proxy-eps" . }}
  labels:
    {{- include "iris-gateway.public-proxy-eps-labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.publicProxy.nodePortEps }}
      targetPort: node-port-eps
      nodePort: {{ .Values.publicProxy.nodePortEps }}
      protocol: TCP
      name: node-port-eps
    - port: {{ .Values.publicProxy.jsonRpcPortEps }}
      targetPort: json-rpc-eps
      protocol: TCP
      name: json-rpc-eps
  selector:
    {{- include "iris-gateway.public-proxy-eps-labels" . | nindent 4 }}
