# https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image

name: Build and package image for iris-client-sormas-sidecar and publish it to docker.io

on:
  push:
    branches:
      - main
    paths:
      - iris-client-sormas-sidecar/**
      - .github/workflows/client-sormas-sidecar_develop.yml

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    
      - name: build parent POM (only) for the following builds
        run: mvn -B -N install --file pom.xml
    
      - name: build and run IRIS API generator
        run: mvn -B install --file iris-api-generator/pom.xml
    
      - name: build IRIS API sidecar client
        run: mvn -B install --file iris-api-sidecar-client/pom.xml
    
      - name: build sormas API client
        run: mvn -B install --file iris-sormas-api-client/pom.xml
        
      - name: build, package and publish the image
        run: mvn -B spring-boot:build-image --file iris-client-sormas-sidecar/pom.xml -Dspring-boot.build-image.publish=true -DskipTests
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PW }}
