name: Copies infrastructure scripts to VM

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
      - .github/workflows/copy-infrastructure-scripts.yml

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_PW }}
          ARGS: "-rltzO --delete"
          SOURCE: "infrastructure/"
          REMOTE_HOST: iris-gateway.de
          REMOTE_USER: ${{ secrets.STAGING_USER }}
          TARGET: /home/iris/infrastructure/
