# https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image

# Build and package image for demo-contact-diary-app and deploy it to docker.io
name: demo-contact-diary-app Develop

on:
  push:
    branches:
      - main
    paths:
      - demo-contact-diary-app/**
      - .github/workflows/demo-contact-diary-app.yml

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'maven'

      - name: build, package and publish the image
        run: >
          mvn -B clean verify spring-boot:build-image -am -pl demo-contact-diary-app
          -Dspring-boot.build-image.publish=true
          -Dversion.tag="develop"
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PW }}

  container_scan:
    needs: build
    name: Trivy Container Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'inoeg/demo-contact-diary-app:develop'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '1'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
