name: Fetch RKI XML

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 1'

jobs:
  fetch_rki_xml:
    name: Fetch RKI XML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and Unzip
        uses: schmiddim/action-wget-unzip@v2
        with:
          url: 'https://survnet.rki.de/Content/Service/DownloadHandler.ashx?Id=82'
          destination: 'iris-backend-service/src/main/resources/masterdata'
      
      - name: Fix encoding and formatting
        uses: pipeline-components/xmllint@v0.6.2
        with:
          directory: iris-backend-service/src/main/resources/masterdata/TransmittingSiteSearchText.xml
          options: --format --encode utf8 -o iris-backend-service/src/main/resources/masterdata/TransmittingSiteSearchText.xml

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'maven'

      - name: build and test backend service
        run: mvn -B clean verify -am -pl iris-backend-service
          
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            **/surefire-reports/*.xml
            **/failsafe-reports/*.xml
            !**/failsafe-reports/failsafe-summary.xml
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: iris-backend-service/src/main/resources/masterdata/TransmittingSiteSearchText.xml
          commit-message: 'fix: updates the RKI XML for HD search'
          branch: chore/update_rki_xml
          delete-branch: true
          title: 'Updates the RKI XML for HD search'
          body: |
            Updates the RKI XML for HD search with the current version from  
            https://survnet.rki.de/Content/Service/DownloadHandler.ashx?Id=82
            
            Auto-generated by [create-pull-request]

  publish-test-results:
    name: Publish Test Results
    needs: fetch_rki_xml
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-reports
          path: reports

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: reports/**/*.xml
          report_individual_runs: true
          check_run_annotations_branch: "*"
