name: Fetch RKI XML

on:
  push:
    branches: [ feat/263-plz_hd_search ]
  workflow_dispatch:
  schedule:
    - cron: '48 * * * *'
#    - cron: '30 2 * * 1'

jobs:
  fetch_rki_xml:
    name: Fetch RKI XML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Download and Unzip
        uses: schmiddim/action-wget-unzip@v2
        with:
          url: 'https://survnet.rki.de/Content/Service/DownloadHandler.ashx?Id=82'
          destination: 'iris-backend-service/src/main/resources/masterdata'
      
      - name: Fix encoding and formatting
        uses: pipeline-components/xmllint@v0.1.0
        with:
          directory: iris-backend-service/src/main/resources/masterdata/TransmittingSiteSearchText.xml
          options: --format --encode utf8 -o iris-backend-service/src/main/resources/masterdata/TransmittingSiteSearchText.xml
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: iris-backend-service/src/main/resources/masterdata/TransmittingSiteSearchText.xml
          commit-message: 'fix: updates the RKI XML for HD search'
          branch: chore/update_rki_xml
          delete-branch: true
          title: 'Updates the RKI XML for HD search'
          body: |
            Updates the RKI XML for HD search with the current version from  
            https://survnet.rki.de/Content/Service/DownloadHandler.ashx?Id=82
            
            Auto-generated by [create-pull-request]
