name: Build, package and publish location service on push to develop branch

on:
  push:
    branches:
      - develop
    paths:
      - iris-backend-service/**
      - .github/workflows/iris-backend-service.yml

jobs:
  # https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image
  build-backend-service:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Cache local Maven repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: build, package and publish the image
        run: >
          mvn -B spring-boot:build-image -am -pl iris-backend-service
          -Dspring-boot.build-image.publish=true
          -Dversion.tag="develop"
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PW }}

  container_scan:
    needs: build-backend-service
    name: Trivy Container Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'inoeg/iris-backend-service:develop'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
