# https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#build-image

name: Build and package image for iris-public-server and deploy it to docker.io

on:
  push:
    branches:
      - main
    paths:
      - iris-app-api-demo/**
      - .github/workflows/iris-app-api-demo.yml

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    
      - name: build, package and publish the image
        run: mvn -B spring-boot:build-image --file iris-app-api-demo/pom.xml -Dspring-boot.build-image.publish=true -DskipTests
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PW }}
